/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-southeast-1",
    "aws_cognito_identity_pool_id": "ap-southeast-1:cd6aa0a5-ae12-49ae-be14-d410d8e2c67d",
    "aws_cognito_region": "ap-southeast-1",
    "aws_user_pools_id": "ap-southeast-1_VKIgAQw0f",
    "aws_user_pools_web_client_id": "51n3llf3b49f3doojigk2mu2pj",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://q3etpwxwazhcvln22n4mczmmhy.appsync-api.ap-southeast-1.amazonaws.com/graphql",
    "aws_appsync_region": "ap-southeast-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-bwalro2ktbcppjdhmxtztr5f2u",
    "aws_user_files_s3_bucket": "ayakata2165613-dev",
    "aws_user_files_s3_bucket_region": "ap-southeast-1",
    "Auth": {
        "identityPoolId": "ap-southeast-1:d5585b9f-d11f-4d3a-9fec-9b069010a8c1",
        "region": "ap-southeast-1"
    },
    "Storage": {
        "AWSS3": {
            "bucket": "ayakata",
            "region": "ap-southeast-1"
        }
    }
};


export default awsmobile;
